
var sub = (num1,num2)=>num1-num2;

var add = (num1,num2)=>{
    return num1+num2;
}
var power = (num1,num2)=>
{
    return Math.pow(num1,num2);
}

welcome = () => "Welcome";
squar = (num) => num*num;
greetings = (name) => "Hello"+name;

console.log(power(2,2));

console.log(welcome());
console.log(sub(5,6));
console.log(squar(4));
console.log(greetings(" raj"));

//Array Operations

var arry1=[0,2,5,6];

console.log(arry1);
console.log(arry1.length);
console.log(arry1.length-1);
var arr3 = ["Shiju","Anil","Pecok"];
console.log(arr3)